ingress:
  enabled: true
  path: "/"

service:
  enabled: true
  externalPort: 3000
  internalPort: 3000

extraEnv:
 - name:  REACT_APP_FETCH_URL
   value: https://figvam-go-curl.figvam.ru/api/v1/search